version: "3.9"

services:
    app:
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=rest_api
            - DB_USER=django
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=rest_api
        ports:
            - "5432:5432"
        volumes:
            - dev-db-data:/var/lib/postgresql/data

volumes:
    dev-db-data:            